const CategoryActionsType = {
  UPDATE_LOADING_BRANCH: "UPDATE_LOADING_BRANCH",
  UPDATE_BRANCH_DATA: "UPDATE_BRANCH_DATA",
  UPDATE_VALIDATE_BRANCH: "UPDATE_VALIDATE_BRANCH",
  UPDATE_BRANCH_DESCRIPTION: "UPDATE_BRANCH_DESCRIPTION",
  UPDATE_BRANCHS: "UPDATE_BRANCHS",
  UPDATE_DETAIL_BRANCH: "UPDATE_DETAIL_BRANCH",
  UPDATE_SEARCH_ID: "UPDATE_SEARCH_ID",
};

export default CategoryActionsType;
