const actionTypes = {
  UPDATE_LOADING_IMAGES: "UPDATE_LOADING_IMAGES",
  UPDATE_IMAGES: "UPDATE_IMAGES",
  UPDATE_SELECTED_IMAGE: "UPDATE_SELECTED_IMAGE",
  UPDATE_FILTER_IMAGES: "UPDATE_FILTER_IMAGES",
};

export default actionTypes;
