version: "3.9"
name: "goattap"

services:
  goattap_db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: goattap
      POSTGRES_PASSWORD: Aaaa@1111
    ports:
      - 5432:5432
    volumes:
      - ./server/builtIn/goat-tap-api/scripts/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    networks:
      - goattap

  goattap_api:
    build:
      context: .
      dockerfile: server/builtIn/goat-tap-api/Dockerfile
    environment:
      PORT: 6789
      NODE_ENV: production
      DB_HOST: goattap_db
      DB_PORT: 5432
      DB_USER: goattap
      DB_PASSWORD: Aaaa@1111
      DB_DATABASE: goattap
      REDIS_HOST: redis
      REDIS_PORT: 26379
      REDIS_GLOBAL_TTL: 3600
      REDIS_PASSWORD: "!pH9ukH8S_%drh24"
      CORS_ORIGIN: "*"
      CORS_CREDENTIALS: true
      JWT_SECRET: "upgrade cat walk usage you weird blood reject gift spawn food liberty south edit barrel weasel slice dwarf arena say tobacco"
      JWT_EXPIRATION: 7884000
      JWT_ISSUER: https://goattap.io
      JWT_AUDIENCE: JWT_APIs
      TELEGRAM_BOT_TOKEN: 7280606478:AAHaRTnPVK6G263MsL8bO2uUqMHtJJfFB6E
    depends_on:
      - goattap_db
    ports:
      - 6789:6789
    command: ["pnpm", "run", "server:build"]
    networks:
      - goattap

  goattap_client:
    build:
      context: .
      dockerfile: apps/goat-tap/Dockerfile
    environment:
      VITE_BASE_URL: https://192.168.137.1:5173
      VITE_API_URL: http://goattap_api:6789
      VITE_TELEGRAM_BOT_URL: https://t.me/goattapdevbot
      VITE_TELEGRAM_BOT_WALLET_ADDRESS: UQDozoVJzP-Va28QA8A3OG01ebBH31h1ofxb2wmzKYx-3pVK
      VITE_IS_TEST_NET: true
      PRIVATE_KEY_PATH: ../../../../../private-key.pem
      CERTIFICATE_PATH: ../../../../../certificate.pem
    depends_on:
      - goattap_api
    volumes:
      - ./apps/goat-tap:/apps/goat-tap:delegated
    ports:
      - 80:80
    command: ["pnpm", "run", "start:dev"]
    networks:
      - goattap

networks:
  goattap:
    driver: bridge
