packages:
  # all packages in direct subdirs of packages/
  # - "client/**"
  - "client/lib/api-client"
  - "client/lib/react-hooks"
  - "client/lib/react-social-login"
  - "client/sdk/core"
  - "client/sdk/novels"
  - "client/sdk/jobs-listing"
  - "client/ui/mui/react-core-mui"
  - "client/ui/react-animates"
  - "client/ui/react-context"
  - "client/ui/react-core"
  - "client/ui/react-mobx-state"
  - "client/ui/react-viewFrames"
  - "client/ui/react-lazyload"
  - "client/builtIn/react-novels"
  - "client/builtIn/react-jobs-listing"

  # all packages in subdirs of components/
  - "server/libs/*"
  - "server/domain/api-authentication"
  - "server/domain/api-appcenter-gateway"
  - "server/domain/api-goat-tap"
  - "server/domain/api-novels"
  - "server/domain/api-recruiter"
  - "server/domain/api-ums"
  - "server/modules/**"
  - "server/nestjs/**"

  # all packages in subdirs of shared/
  - "shared/**"

  # all packages in direct subdirs of packages/
  #- "apps/**"
  - "apps/novels"
  - "apps/goattap"
  - "apps/jobs-listing"
  
  # exclude packages that are inside test directories
  - "!**/test/**"
