packages:
  # all packages in direct subdirs of packages/
  # - "client/**"
  - "client/lib/api-client"
  - "client/lib/react-hooks"
  - "client/lib/react-social-login"
  - "client/sdk/core"
  # - "client/sdk/novals"
  - "client/sdk/jobs-listing"
  - "client/ui/mui/react-core-mui"
  - "client/ui/react-animates"
  - "client/ui/react-context"
  - "client/ui/react-core"
  - "client/ui/react-mobx-state"
  - "client/ui/react-viewFrames"
  - "client/ui/react-lazyload"
  # - "client/builtIn/react-novals"
  - "client/builtIn/jobs-listing"

  # all packages in subdirs of components/
  # - "server/builtIn/novals-api"
  # - "server/builtIn/novals-gateway"
  - "server/builtIn/jobs-listing-api"
  - "server/nestjs/*"
  - "shared/**"

  # all packages in direct subdirs of packages/
  #- "apps/**"
  # - "apps/novals"
  # - "apps/goattap"
  - "apps/jobs-listing"
  
  # exclude packages that are inside test directories
  - "!**/test/**"
