packages:
  # all packages in direct subdirs of packages/
  # - "client/**"
  - "client/lib/api-client"
  - "client/lib/react-hooks"
  - "client/lib/react-social-login"

  # - "api-sdk/**"
  - "client/sdk/core"

  # client packages
  - "client/ui/mui/react-core-mui"
  - "client/ui/react-animates"
  - "client/ui/react-context"
  - "client/ui/react-core"
  - "client/ui/react-mobx-state"
  - "client/ui/react-viewFrames"
  - "client/ui/react-lazyload"
  - "client/ui/react-charts"
  - "client/ui/react-flow"
  
  # business logic package
  - "client/builtIn/react-novels"
  - "client/builtIn/react-ums"
  - "client/builtIn/react-auth"
  - "client/builtIn/react-recruiter"

  # all packages in subdirs of shared/
  - "shared/**"

  # all packages in direct subdirs of packages/
  - "apps/demo"

  # exclude packages that are inside test directories
  - "!**/test/**"
