version: '3.3'
services:
  goattap_db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: goattap
      POSTGRES_PASSWORD: Aaaa@1111
    ports:
      - 25432:5432
    volumes:
      - ./scripts/initial.sql:/docker-entrypoint-initdb.d/initial.sql

    networks:
      - goattap
networks:
  goattap:
    driver: bridge
