const CategoryActionsType = {
  UPDATE_LOADING_CATEGORY: "UPDATE_LOADING_CATEGORY",
  UPDATE_CATEGORY_DATA: "UPDATE_CATEGORY_DATA",
  UPDATE_VALIDATE_CATEGORY: "UPDATE_VALIDATE_CATEGORY",
  UPDATE_CATEGORY_PARENT: "UPDATE_CATEGORY_PARENT",
  UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
  UPDATE_DETAIL_CATEGORY: "UPDATE_DETAIL_CATEGORY",
  UPDATE_SEARCH_ID: "UPDATE_SEARCH_ID",
};

export default CategoryActionsType;
