const HomeActionsType = {
  UPDATE_LOADING_UICONFIG: "UPDATE_LOADING_UICONFIG",
  UPDATE_UICONFIG_DATA: "UPDATE_UICONFIG_DATA",
  UPDATE_HOME_PAGE_CONFIG: "UPDATE_HOME_PAGE_CONFIG",
};

export default HomeActionsType;
