const ProductActionsType = {
  UPDATE_LOADING_PRODUCT: "UPDATE_LOADING_PRODUCT",
  UPDATE_PRODUCT_DATA: "UPDATE_PRODUCT_DATA",
  UPDATE_VALIDATE_PRODUCT: "UPDATE_VALIDATE_PRODUCT",
  UPDATE_PRODUCT_DETAIL: "UPDATE_PRODUCT_DETAIL",
};

export default ProductActionsType;
